### ISSUE TITLE
On initialize screen, on bottom it shows Powered by but the RightMesh part is cutoff

### ISSUE THREAD

**Issue by ConnorHeidema** [RightMesh/meshIM#14]
My personal nexus 5 doesn't display the initialising screen with the RightMesh logo or name on the bottom. 
![screenshot_20180216-113512](https://user-images.githubusercontent.com/33189633/36325942-3c27299a-130e-11e8-8a2e-c4f6defef7e9.png)

**Comment by FrazerSeymour** [comment]
Thanks! We'll take a look.
