### ISSUE TITLE
Onboarding doesn't change an already set username

### ISSUE THREAD

**Issue by compscidr** [RightMesh/meshIM#2]
When the app is reinstalled, the username doesn't update correctly on the onboarding process. It does change correctly when going to the account screen.

Also, if there is already account information - should the onboarding screen even show?

**Comment by FrazerSeymour** [comment]
Fixing in #11.

**Comment by FrazerSeymour** [comment]
To your second question, it won't show if there is already account information saved on the phone.

When testing, this means that redeploying the app in Android Studio will _not_ cause it to show the onboarding again, but completely uninstalling the app then redeploying it _will_ (as SharedPreferences are removed from the device).

**Comment by FrazerSeymour** [comment]
Fixed with #11.
