### ISSUE TITLE
Update the interface state to reflect that there are unread messages.

### ISSUE THREAD

**Issue by FrazerSeymour** [RightMesh/meshIM#24]
Message list mocks here: invis.io/JSF6GLYAE#/screens/272868904

Would also be useful to add a boolean `Read` column to the database so this persists when the app closes.

**Comment by FrazerSeymour** [comment]
@JMortemore or @llefurgeysmith - would a badge of some kind in the messages tab be appropriate?

**Comment by JMortemore** [comment]
Yeah, a badge on the messages tab makes a lot of sense if you are in the app and have something new arrive. As opposed to the push notification.

**Comment by FrazerSeymour** [comment]
Do we have a badge icon or anything already?

**Comment by JMortemore** [comment]
Mockup here [https://invis.io/JSF6GLYAE#/272868902_In_Range](url)
Just a 8x8px dot with a drop shadow that appears if you are on the In Range or Account tab and receive a new message. Does not track number of messages - they are either there or not.
