### ISSUE TITLE
UI Polish items

### ISSUE THREAD

**Issue by JMortemore** [RightMesh/meshIM#28]
- [x] Increase vertical space between avatars on selection page so they are not touching. 
- [x] Available icon on Account screen squished vertically
- [x] Bottom tab navigation: Show active text and icon in same green colour 00AA81, and inactive text/icon pairs in inactive grey colour 9E9E9E
- [x] Edit username - text box that shows should come up with current username in text field, and keyboard active to allow fast editing. 
- [x] Differentiate bottom tab navigation from screen content with a drop shadow
- [ ] Increase time for showing splash screen - currently shows too fast to register.

**Comment by FrazerSeymour** [comment]
RE splash screen - is that a bad thing?

I was under the impression that splash screens are a bad thing, and you show them only as long as you need to load your app.

**Comment by JMortemore** [comment]
A fast load time is not a bad thing. What I meant was that because it loads so fast, you can't actually read the content on the screen. Don't worry about it - would be worth looking at on some different devices... possible solution if needed would be to have a mainly blank loading screen instead of showing logo.

**Comment by FrazerSeymour** [comment]
Is there a minimum time you want it displayed?
