### ISSUE TITLE
Notification not showing when service is running foreground on Android 8.0

### ISSUE THREAD

**Issue by FrazerSeymour** [RightMesh/meshIM#30]
Neither the RightMesh nor meshIM notifications display on at Android 8.0. On my device a notification pops up that meshIM is running in the background (so perhaps has entered foreground mode) but there is no in-app way to stop the service. Likely has to do with the notification API changes the @compscidr started addressing earlier.

**Comment by compscidr** [comment]
If this is the case, its likely fixed by updating to compile against the 0.4.3 version of the lib. Also we might want a way to easily determine which version of the lib the apk is compiled against.

**Comment by FrazerSeymour** [comment]
Pretty sure the APK was built with `0.4.3`. I'll maybe deploy a build right to my phone tomorrow and see how that goes.
