### ISSUE TITLE
Notification of new message takes us to the contact list, not the correct conversation

### ISSUE THREAD

**Issue by compscidr** [RightMesh/meshIM#4]
See title. When a notification for a new message arrives, it should take us directly into the correct conversation. Also it would be nice if the contact list also showed some indication if there are new messages which are still unread.

**Comment by FrazerSeymour** [comment]
First should be an easy fix, second is in the backlog already. :+1:

**Comment by FrazerSeymour** [comment]
Should we port our Jira backlog to somewhere public like Trello or whatever GitHub's tracking system is? Would be useful for differentiating bugs/feature requests that are in the works vs. new.

**Comment by ghost** [comment]
I fixed the first part of the issue. once I  am done with merging the changes I will take a look at the second part of this issue as a separate issue

**Comment by FrazerSeymour** [comment]
Oh yeah for sure, missed that that was in this ticket.

**Comment by FrazerSeymour** [comment]
Excellent, so the `fixes #4` commit message approach automatically moves it in the project. :+1:
