### ISSUE TITLE
Add the ability to save/pin users on the online users list screen.

### ISSUE THREAD

**Issue by compscidr** [RightMesh/meshIM#5]
It might be better if the contacts stayed in the list, but their status changed to a red offline status for when they leave the mesh (this way you can still "send" them messages which will be delivered when the peer comes back online).

Also havent tested this yet, but it would be cool if there was an orange, out of range but reachable via the Internet type of status.

Finally for the first part, when @sriks1 gets the send notification event to work on the library side it would be great if you could keep track locally whether the message was successfully received. Then you would be able to to send all undelivered messages when a peer comes online again.

**Comment by FrazerSeymour** [comment]
"Contacts" being people you've exchanged a message with, or just anyone you encounter? The first I might be on board with, the latter could lead to a page with a boatload of people on it that you don't care about but were in range with once.

In the mocks there's a button for "compose a new message" in the conversations tab, I wonder if the screen that leads to can give you the option to search through everyone you've ever come across so you can access them when they aren't in range and you haven't exchanged a message with them.

"In range on the internet" would be cool, but again - _everyone_ available on the internet? Or just people you've spoken to before? Locally we can limit "nearby" by hop-count but like do we have hop-count over the internet as well?

Finally, store and forward is in the backlog. :+1: Definitely something we're planning for in the near future.

**Comment by compscidr** [comment]
Probably exchanged a message with - but maybe you might want to "pin" other people without sending them a message so that you can follow their online / offline / internet connected status

**Comment by FrazerSeymour** [comment]
I was wondering about "pin/save/favourite" as well. We can bug Jenna for design thoughts.

**Comment by JMortemore** [comment]
I personally like the idea of tying this to starting a new conversation, so a conversation does not have to be initiated from the In Range screen all the time. 

Add in the FAB with a + icon to the Messages screen. Tapping on this can open to a searchable list of "Contacts" - in this case, it can just show the usernames and avatars for anyone that you run into on RightMesh, listed alphabetically. 

Up for debate: this could be limited to only show people who you have had a personal messages history with.
